### ISSUE TITLE
Ошибка возможно связаная с состоянием подключения аппарата

### ISSUE THREAD

**Issue by lirik90** [WorkerBeesTeam/DaiServerWebFront#100]
![изображение](https://user-images.githubusercontent.com/3821904/123896984-d2c97900-d98c-11eb-9a82-6326193cd88a.png)
Вылазит какая то ошибка. Однажды поймал и на отладочной сборке, но файл и номер строки не успел записать. (

**Comment by lirik90** [comment]
![изображение](https://user-images.githubusercontent.com/3821904/124350510-4a163b80-dc1f-11eb-9e2d-e08116877b1a.png)

**Comment by lirik90** [comment]
![изображение](https://user-images.githubusercontent.com/3821904/124350659-1687e100-dc20-11eb-9615-b831201392e5.png)
Вот ещё. Зашёл на аппарат UFarm Кондиционер во вкладку Сведения

**Comment by lirik90** [comment]
![изображение](https://user-images.githubusercontent.com/3821904/124350677-315a5580-dc20-11eb-9a0e-2d88863e0de1.png)
Это тот же аппарат страница Мнемосхемы (Обзор)

**Comment by ByMsx** [comment]
@lirik90 ошибку на `schemes-list` воспроизвести не удалось. Остальные поправил.
