### ISSUE TITLE
Мнемосхемы: Приводить строку к соответствующему типу

### ISSUE THREAD

**Issue by lirik90** [WorkerBeesTeam/DaiServerWebFront#108]
В xml svg значения задаются как текст и потом при сравнивании значения с значением элемента устройства некоректное значение получается. Нужно это значение из SVG пытаться привести к типу значения элемента устройства.

**Comment by ByMsx** [comment]
@lirik90 
Опиши, пожалуйста, проблему подробнее. В проверках для включения/отключения анимации используется нестрогая проверка данных (`==`), которая игнорирует типы (`'1' == 1` - `true`). Возможно, есть какой-то другой баг, но нужно больше информации для его поиска.

**Comment by lirik90** [comment]
Да, чот с привидением я погорячился наверно. Хотя это казалось логичным, возможно была какая-то причина. Всё что помню, это то что на многих аппаратах дверь не отображается. Посмотри пожалуйста почему. @ByMsx

**Comment by ByMsx** [comment]
@lirik90 
В "салате" (svg) на строке 165 нужно поставить `data-show-if-value="1"`, на строке 128 (`door_close`) нужно поставить `data-show-if-value="0"`.
