### ISSUE TITLE
Баг на графике после обновления

### ISSUE THREAD

**Issue by lirik90** [WorkerBeesTeam/DaiServerWebFront#111]
![изображение](https://user-images.githubusercontent.com/3821904/124409843-5c08f300-dd73-11eb-9553-f0b46206bb1d.png)
Появился какой то отступ слева и справа на графике. Нужно попробовать взять эталонный график из примера библиотеки и посмотреть есть ли баг у них. Если есть, написать им куда-нибудь сообщение (issue например). Если нет, то попытаться разобраться в какой момент этот отступ появляется и по возможности пофиксить это.

**Comment by lirik90** [comment]
![изображение](https://user-images.githubusercontent.com/3821904/124410853-7d6ade80-dd75-11eb-9af5-03eb1965c159.png)

**Comment by lirik90** [comment]
![изображение](https://user-images.githubusercontent.com/3821904/124412339-78f3f500-dd78-11eb-9b76-805f75ccb8c3.png)
Видать поторопился я с желанием обновить Chart.JS, они версии новыше штопают как пирожки. Видать баги закрывают. Обновись сразу в рамках этой задачи. Может что пофиксится. =)

**Comment by ByMsx** [comment]
@lirik90 
Поправил ошибки из консоли, обновил chart.js (PR #112) 
По поводу отступов: 
- у графиков типа line в примерах нет отступов (https://www.chartjs.org/docs/latest/samples/line/line.html);
- у графиков типа bar они есть (https://www.chartjs.org/docs/latest/samples/bar/vertical.html).

Что я сделал?
1) попробовал отключить плагин zoom;
2) попробовал задать `padding: 0`;
3) попробовал задать `responsive: false`;
4) проверил есть ли данные за гранью этого "отступа";
5) проверил влияние CSS;
6) что-то ещё по мелочи;
7) попробовал отключить `setViewportBounds`;
8) перечитываю StackOverflow от Chart.js, нашел что-то похожее.

**Comment by ByMsx** [comment]
@lirik90 
Попробовал всякие варианты из ответов на StackOverflow + запостил свой вопрос (https://stackoverflow.com/questions/68261323/strange-padding-at-chart-area-after-updating-chart-js-2-8-0-3-4-1)

**Comment by lirik90** [comment]
@ByMsx Проверил, ответ на StackOverflow. Рабочий!
```js
options: {
  scales: {
    x: {
      offset: false 
    }
  }
}
```

**Comment by ByMsx** [comment]
@lirik90 , запушил в PR.
