### ISSUE TITLE
Мануал по основной терминалогии с видео

### ISSUE THREAD

**Issue by lirik90** [WorkerBeesTeam/DaiServerWebFront#116]
Первым этапом нужен красивый текстовый мануал с картинками. Вторым его видео-вариант. Но предварительно нужно подготовить материалы в приложеном файле:
1. В коде и интерфейсе у нас сейчас используется термин Device_Item (Элемент устройства). В мануале и видео нужно использовать Device_Data_Item (Элемент данных устройства). Позже заменим термин и в коде.
2. В коде и интерфейсе есть термин DIG Device Item Group (Группа элементов устройства), этому термину была предложена замена (Контур управления) - нужно попробовать найти информацию о том используется ли такой термин в АСУТП и вообще в ИТ. И если используется, то попробовать найти его вариант в английском языке (может в википедии или в английской тех.литературе). Если удастся, то в мунуале нужно использовать эти термины, позже заменим их и в коде. Если не удастся, то использовать "Контур управления (Device Item Group)"
3. Подумать на сколько разумно было бы заменить термин Схема на Конфигурация. И если ты считаешь что в этом есть смысл, то в мануале использовать "Конфигурация (Configuration)". А если нет, то "Схема (Конфигурация, Scheme)"

Приложенный файл читать до раздела "Части системы" - это и дальше уже всё не нужное для мануала. 

В мануале и видео наверное надо сначала кратко дать определение всех терминов, а затем по каждому термину подробно, с указанием (Скринами) где на сайте эти термины фигурируют. Например Схема (или Конфигурация) это в частности сущности (строки) на таких страницах как Список и Избранное.

[Описание софта (17.09.2020).docx](https://github.com/WorkerBeesTeam/das_front/files/6771902/17.09.2020.docx)

**Comment by ByMsx** [comment]
@lirik90 , заполняю док. Вопрос такой: мануал - это описание функциональности всех возможных окон?

**Comment by ByMsx** [comment]
@lirik90 , "подготовить материалы" – это собрать нормативку или попытаться дать определение?

**Comment by lirik90** [comment]
@ByMsx Все термины и их определения уже даны в файле. Если можешь улучшить, отлично, если нет бери как в файле. Только прежде разберись с пунктами в задаче.
