### ISSUE TITLE
Переключатель "Редактировать схему" отображается у user

### ISSUE THREAD

**Issue by ByMsx** [WorkerBeesTeam/DaiServerWebFront#125]
Переключатель должен отображаться только у администратора.

**Comment by ByMsx** [comment]
@lirik90 

Возможно, на моём user-пользователе есть лишние права, поэтому переключатель и показывается.
```javascript
return this.checkPermission('change_logentry');
```
Это код проверки `isAdmin()`. Или для редактирования схемы есть отдельные права?

**Comment by lirik90** [comment]
Добавил права restart
