### ISSUE TITLE
Графики: Не добавляется текущее значение если ts_to больше или равен текущему времени

### ISSUE THREAD

**Issue by lirik90** [WorkerBeesTeam/DaiServerWebFront#64]
Нужно проверить добавляется ли текущее значение из схемы к ответу сервера на запрос крайних значений, если запрашивается диапазон вплоть до текущего времени. 
Этапы повторения бага:
1. Открываем графики.
2. Добавляем уставки (например Темперетура - Днём).
3. Нажимаем построить график.
4. Видим что в ответе сервера есть значение до, но на графике никакой линии не рисуется.

**Comment by ByMsx** [comment]
@lirik90 на каком сервере/схеме это лучше тестировать?

**Comment by lirik90** [comment]
@ByMsx На боевом конечно, так как при тесте не нужно вносить никакие изменения в данные, а только запрашивать их. Схему выбери любую подключеную.

**Comment by lirik90** [comment]
На самом деле нужно добавлять текущую точку даже если запрошеный диапазон времени далеко в прошлом, а сервер всё равно не вернул последнее значение. Значит считаем что значение за всё время не изменилось и надо брать текущее. Поправил сразу в develop.
