### ISSUE TITLE
Уставки с чекбоксом не обновляются в схеме из памяти при удачном сохранении

### ISSUE THREAD

**Issue by lirik90** [WorkerBeesTeam/DaiServerWebFront#65]
Нужно посмотреть сохранение уставок с чекбоксом. Там какая то проблема именно с чекбоксами.
Этапы повторения бага:
1. Заходим в уставки группы "Полив"
2. Ставим галочку "Инверсия датчика уровня раствора"
3. Нажимаем сохранить. Видим что сохраняется успешно без таймаута.
4. Опять заходим в те же уставки и видим что галочка установленна как и должно быть.
5. Снимаем галочку и нажимаем сохранить. Видим что сохраняется успешно без таймаута.
6. Заходим опять туда же и видим что галочка стоит как буд то мы её не снимали.
Страницу при этом не обновлять!

**Comment by ByMsx** [comment]
@lirik90 , c сервера по web-сокету приходят `"false"` или `"true"` в виде строк, а не в виде булевых значений: `false` или `true`. Можно добавить преобразование в метод `ByteTools.parseQString()`, если это не баг сервера.

**Comment by lirik90** [comment]
@ByMsx добавь пожалуйста пока тупо условие : если тип уставки булево значение и значение пришло текстовое, то берем за значение false если пришло "false" или "0", всё остальное true.
