### ISSUE TITLE
График должен занимать всё доступное видимое пространство, но не более того.

### ISSUE THREAD

**Issue by lirik90** [WorkerBeesTeam/DaiServerWebFront#71]
На мобильных телефонах с повёрнутым экраном график уезжает вниз. Нужно сделать так чтобы график был в высоту (и в ширину) не больше доступного видимого поля, с учётом обеих панелей в шапке сайта.

При использовании панели разработчика этот глюк тоже проявляется, т.е. показывается скролбар. У меня даже в каком то положении показывается два, а иногда даже появляется какой то дребезг (страница дёргается постоянно и скролбар то появляется, то исчезает). Именно на странице с графиками нужно в классе: **.router-outlet-wrap** запретить показывать полосу прокрутки:
![изображение](https://user-images.githubusercontent.com/3821904/116973555-ee930480-ace6-11eb-95d5-c788eaeb1ab7.png)

**Comment by ByMsx** [comment]
@lirik90 , не удалось запретить скролл для `.router-outlet-wrap`, однако, баг исправлен. #83
