### ISSUE TITLE
На странице с мнемосхемами выводить текст если нет ни одной.

### ISSUE THREAD

**Issue by lirik90** [WorkerBeesTeam/DaiServerWebFront#73]
Если сервер не вернул ни одной схемы, то выводить текст "Нет ни одной".

**Comment by ByMsx** [comment]
@lirik90 проверить не удалось, т.к. на тестовом сервере не хватает прав `view_mnemoscheme`, но есть `menu_mnemoscheme`. На проде вообще никаких.
