### ISSUE TITLE
Баг при сохранении скриптов

### ISSUE THREAD

**Issue by lirik90** [WorkerBeesTeam/DaiServerWebFront#88]
1. При сохранении ошибка и окно остаётся как будто не сохранено. 
2. Второй баг если попытаться уйти со страницы и нажать нет не сохранять, то он возвращает на эту же страницу.
3. Если нажать на крестик, т.е. отменить правку, то сворачивается код, а крестик не исчезает (т.е. не нажался) и только если нажать ещё раз, то он нажимается.

**Comment by ByMsx** [comment]
@lirik90 
1) Fixed
2) Не удалось повторить. При нажатии на "Забыть" переносит туда, куда хотел.
3) Fixed

PR #97
